### ISSUE TITLE
docker-compose environment variables

### ISSUE THREAD

**Issue by Guido83** [ubc/mediawiki-docker#23]
I am using your docker-compose.yaml and got the problem, that none of the environment variables seems to be passed.
after bringing up the stack, my LocalSettings.php does not contain any of the environment variable settings correctly.
furthermore the admin user does not have any permission on the mediawiki, not even the one to create a new site

**Comment by xcompass** [comment]
How did you tell the LocalSettings.php doesn't contain any env vars? What was the command did you use for run your docker-compose.yaml? What's your environment? e.g. linux, osx or windows? What's your docker/docker-compose version? I can try to replicate the issue locally.

**Comment by Guido83** [comment]
Thank you for your reply.
maybe I'm wrong with the env vars not in the LocalSettings.php, but for instance when I set env var MEDIAWIKI_SITE_LANG=de, the LocalSettings.php has it set to "en" anyway.

Let me explain how I'm building up the stack:
It is a linux OS and I always use portainer to create the stack which only supports docker-compose v2.
After all containers are up and the "user_cwl_extended_account_data" table is added sucessfully to the database, I need to cp the LocalSettings.php out of the container into my shared volume. After this I uncomment the line which mounts the LocalSettings.php in shared volume and I restart all containeiners.
The mediaiki is accessible and I can login as admin with the passwort set in env var  MEDIAWIKI_ADMIN_PASS. But the admin user does not have the permission to create a new wiki entry

**Comment by kitsook** [comment]
Use `MEDIAWIKI_LANGUAGE` to set the site language code. This environment variable will be used to set `$wgLanguageCode` inside LocalSettings.php.

`MEDIAWIKI_SITE_LANG` is only used when the container started for the first time. The docker-entrypoint.sh uses it when running the maintenance/install.php script.

As for the admin user, are you using LDAP authentication or mediawiki local users? Did you specify the admin user name env variable `MEDIAWIKI_ADMIN_USER` the first time you start the container? Otherwise the default admin username is `admin`.
